[[input]]
path="isz.zone"

[[input]]
path="isz.wtf.zone"

[[input]]
path="guest.isz.wtf.zone"

#[[server]]
#name="quentin-ap-1.isz.wtf"
#host="172.30.97.1"
#plaintext_login=true
#old_dns=true

[[server]]
name="router.isz.wtf"
host="172.30.97.3"
plaintext_login=true
